---
title: "Course Information"
---

| CS 181R: Mobile Robotics
| Fall 2024
| Tuesday and Thursday
| 9:35 to 10:50 AM Pacific Time
| ROOM TBD

## Instructors

Professor Anthony Clark ([Research Website](https://cs.pomona.edu/~ajc/))

Here are some quick highlights about me:

- You can call me “Prof Clark” (I also don't mind Dr. Clark or Tony). This is somewhat of a convention on campus, you'll almost never go wrong with “Prof Surname” when referring to your instructors.
- I am originally from the Kansas City area.
- I have a Bachelor of Science (BS) in Computer Engineering from Kansas State University.
- I have a Doctor of Philosophy (PhD) in Computer Science from Michigan State University.
- [I work with my research assistants to build small, robust autonomous robots.](http://anthonyjclark.com/arcs-lab/)

### Teaching Philosophy

I above all aim to be a thoughtful teacher. Here are a few thoughts on my teaching mindset:

- Failure is an important step in learning.
- I can teach you how to be a better learner.
- Lessons are retained longer when learning is harder.
- You will always be supported; you are never alone.
- You are only competing with yourself; you've already "made-it".
- Diversity, equity, and inclusion are important.
- Honest, kind critique is essential to learning (feedback).

### Habits That Help

Here are a few habits that will help you:

- Attending office hours. It helps us both.
- Seeing failure as a source of useful information.
- Focusing on learning not performance.
- Reflecting on your learning habits.
- Regularly self-reflecting and reflecting on materials.
- Getting started early.
- Sticking to a schedule.
- Actively participating in class.
- Have a growth-mindset (failures can be remedied).

See my [advising page](https://anthonyjclark.github.io/advising/) for additional information on CS and being a student at Pomona College.

### Teaching Assistants

- TBD

## Course Description

We will cover the fundamentals of mobile robotics including, societal considerations, electronics, fabrication, kinematics, dynamics, control theory, motion planning, estimation, localization, and vision. Students will build and program a mobile robot to complete a series of tasks. Many of these subjects have broad applications in areas well beyond robotics (e.g., control theory is used in robotics, video games, economics, genomics, medicine, chemistry, etc.).

What you will learn:

- The societal impacts of autonomous systems.
- How to build and program a mobile robot.
- How to model physical systems.
- Basic control theory.
- How to implement math as code.
- How autonomous systems plan and learn.

### Prerequisites

The following courses are required as prerequisites:

- Data structures (CS 62)
- Calculus II (MATH 31)

Exposure to the following subjects would be great, but is not required or anticipated:

- Linear algebra (MATH 60)
- Statistics (MATH 58)
- Vector calculus (MATH 67)
- Computer systems (CS 105)
- Algorithms (CS 140)
- General physics (PHYS 41)
- Mechanics (PHYS 125)
- Engineering (ENGR 79)
- Electronic and Magnetic Circuits and Devices (ENGR 84)
- Digital Electronics and Computer Engineering (ENGR 85)

### Resources for Background Knowledge

Here are some optional background materials if you want to brushup on concepts or prepare yourself for a better appreciation of the topics in this course:

- [Introduction to Applied Linear Algebra](https://www.youtube.com/playlist?list=PLoROMvodv4rMz-WbFQtNUsUElIh2cPmN9)

TODO: find good resources for the following

- Statistics (MATH 58)
- Vector calculus (MATH 67)
- Computer systems (CS 105)
- Algorithms (CS 140)
- General physics (PHYS 41)
- Mechanics (PHYS 125)

## Course Logistics

The general flow of the class will include follow the following routine:

1. Students will "read" (watch embedded lecture videos and read related material) a book chapter before each class period. We will use [Hypothesis](https://web.hypothes.is/) to annotate material with questions and comments.
2. Classes will start with a short quiz to remind students they must complete the pre-class work. Students are allowed to use their "drawing log" on the quiz.
3. We will then have a brief discussion of the material.
4. Students will then work on a hands-on exercise related to the material. We will use a Google Sheet to facilitate questions and help, and the exercise will be due on gradescope by the start of the next class period.

## Grading

This course will have only two assessment categories: quizzes and exercises. Both will be graded using a "nailed it" or "not yet" system. "Nailed it" means that you have mastered the material---you can assume this means you would have received an "A" on the assessment. You can retake quizzes and exercises as many times as you like **up to one week after the original due date.** Final grades will be calculated as:

::: {style="width: 50%;"}

| Grade   | Quizzes   | Exercises   |
| :-----: | --------: | ----------: |
| A       | 25/25     | 25/25       |
| A-      | 24/25     | 24/25       |
| B+      | 23/25     | 23/25       |
| B       | 22/25     | 22/25       |
| B-      | 21/25     | 21/25       |
| C+      | 20/25     | 20/25       |
| C       | 19/25     | 19/25       |
| C-      | 18/25     | 18/25       |
| D+      | 17/25     | 17/25       |
| D       | 16/25     | 16/25       |
| D-      | 15/25     | 15/25       |
| F       | < 15      | < 15        |

:::

Many exercises will be completed with a partner. I reserver the right to adjust your grades if you do not contribute at an appropriate level.

## Policies

### Accommodations

If you have a disability (for example, mental health, learning, chronic health, physical, hearing, vision, neurological, etc.) and expect barriers related to this course, it is important to request accommodations and establish a plan. I am happy to help you work through the process, and I encourage you to contact the [Student Disability Resource Center (SDRC)](https://services.claremont.edu/sdrc/) as soon as possible.

I also encourage you to reach out to the SDRC if you are at all interested in having a conversation. ([Upwards of 20% of students](https://nces.ed.gov/fastfacts/display.asp?id=60) have **reported** a disability.)

### Academic Honesty and Collaboration

I encourage you to study and work on exercises with your peers (unless otherwise specified). If you are ever unsure about what constitutes acceptable collaboration, please ask!

For more information, see the [Computer Science Department](https://www.pomona.edu/academics/departments/computer-science/courses-requirements/academic-honesty) and the [Pomona College](http://catalog.pomona.edu/content.php?catoid=3&navoid=80#Academic_Honesty) policies.

I take violations of academic honesty seriously. I believe it is important to report all instances, as any leniency can reinforce (and even teach) the wrong mindset (*"I can get away with cheating at least once in each class."*).

### Academic Advisory Notice

I will do my best to update you if I think you are not performing at your best or if you are not on pace to pass the class. I will first reach out to you and then use the system built-in to [my.pomona.edu](my.pomona.edu) that will notify your advisor so you are encouraged to work with a mentor or advisor on a plan.

### Attendance

I expect you to attend every class, but I will not directly penalize you for missing class. Know that there is a strong correlation between attendance and grades, and you will almost certainly be indirectly penalized.

You are responsible for any discussions, announcements, or handouts that you miss, so please reach out to me. If you need to leave class early for any reason, please let me know before class begins so that I am not concerned when you leave.

### Late Submissions

Late assignments will not be accepted. However, if you plan ahead you can ask for an extension prior to the assignment deadline (at least four days).

Unless requested ahead of time, some assessments (e.g., quizzes) cannot be completed after the class period in which they are scheduled.
